import { StyleSheet } from "react-native";

export const MainStyles = StyleSheet.create({
  rootContainer: {
    margin: 30,
  },
  title: {
    fontSize: 20,
    fontFamily: "raleway-bold",
    marginTop: 20,
    marginBottom: 10,
  },
  input_box: {
    borderWidth: 1,
    borderColor: "black",
    borderRadius: 10,
    padding: 10,
    flex: 1,
    fontSize: 16,
  },
  image_box: {
    width: 350,
    height: 200,
    borderRadius: 10,
    resizeMode: "cover",
  },
  number_text: {
    fontFamily: "raleway-bold",
    fontSize: 18,
    marginRight: 10,
  },
  ingredient_box: {
    flexDirection: "row",
    alignItems: "center",
    borderRadius: 10,
    padding: 10,
  },
  ing_input_container: {
    flexDirection: "row",
    flex: 9,
  },
  instruction_box: {
    flexDirection: "row",
    alignItems: "center",
    borderRadius: 10,
    padding: 10,
  },
  textInput: {
    fontStyle: "italic",
    fontSize: 16,
    paddingLeft: 10,
  },
  add_ing_container: {
    width: "100%",
    height: 50,
    alignItems: "center",
    justifyContent: "center",
  },
  add_image: {
    width: 30,
    height: 30,
  },
  button_main_container: {
    justifyContent: "center",
    marginTop: 10,
    alignItems: "center",
  },
  button_container: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: 220,
  },
  postButton: {
    backgroundColor: "#FF724C",
    borderRadius: 18,
    padding: 10,
    alignItems: "center",
    width: 100,
  },
  buttonText: {
    color: "black",
    fontFamily: "raleway-bold",
    fontSize: 16,
  },
  success_post_main_container: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "black",
    borderRadius: 10,
  },
  success_post_container: {
    flex: 1,
    width: "100%",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "red",
    borderRadius: 10,
  },
  success_post_text: {
    fontSize: 25,
    fontFamily: "raleway-bold",
    paddingTop: 100,
    marginBottom: 40,
  },
  success_post_image: {
    width: 410,
    height: 310,
    resizeMode: "cover",
    marginBottom: 40,
  },
  back_to_home_button_container: {
    width: 150,
    height: 63,
    borderRadius: 5,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#FF724C",
    marginBottom: 40,
  },
  back_to_home_button_text: {
    color: "black",
    fontFamily: "raleway-bold",
    fontSize: 16,
  },
  see_my_posts_button_container: {
    width: 150,
    height: 63,
    borderRadius: 5,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#242C41",
  },
  see_my_posts_button_text: {
    color: "white",
    fontFamily: "raleway-bold",
    fontSize: 16,
  },
});
